### ISSUE TITLE
Impossible de créer la carte de contact virtual go sites sur la machine de prod

### ISSUE THREAD

**Issue by alkihis** [MMSB-MOBI/martinize-db#26]
L'environnement virtuel Python ne se charge pas et le script plante en conséquences (PyProteinsExt n'existe pas dans le python natif de la machine)
[run_2021-01-01_16-21-49.zip](https://github.com/MMSB-MOBI/martinize-db/files/5759098/run_2021-01-01_16-21-49.zip)

**Comment by cecilpert** [comment]
Resolved by #30
